# SPDX-FileCopyrightText: 2024-2025 Michael Bracht
# SPDX-License-Identifier: MIT

services:
  ocrmypdfwatcher:
    container_name: ocrmypdf-watcher
    image: ocrmypdf-watcher:latest
    restart: always
    volumes:
      - ../input:/input
      - ../output:/output