# SPDX-FileCopyrightText: 2025 Michael Bracht
# SPDX-License-Identifier: MIT

FROM alpine:latest@sha256:a8560b36e8b8210634f77d9f7f9efd7ffa463e380b75e2e74aff4511df3ef88c

# Create ocrmypdf directory
ENV OCRMYPDF_DIR=/ocrmypdf
RUN mkdir -p ${OCRMYPDF_DIR}
WORKDIR ${OCRMYPDF_DIR}

# Install ocrmypdf and German language pack
RUN apk add --no-cache \
        python3=3.12.10-r0 \
        py3-pip=24.3.1-r0 \
        ocrmypdf=16.4.3-r0 \
        tesseract-ocr-data-eng=5.5.0-r0 \
        tesseract-ocr-data-deu=5.5.0-r0

#RUN python3 -m ensurepip
RUN python3 -m pip install --break-system-packages watchdog

# Copy tessdata_best training data
RUN  rm -rf /usr/share/tessdata
COPY external/tessdata_best /usr/share/tessdata

# Install watchdog and watcher Python scrpt
#RUN python -m pip install --no-cache-dir -U watchdog
RUN python -m pip install --break-system-packages --user --upgrade ocrmypdf
COPY src/watcher.py ./

CMD [ "python", "./watcher.py" ]
